### PR TITLE
small fix on cheat fxn

### LINKED ISSUE #67: cheat() doesn't find cheat sheets :(
integral::cheat() isn't working to find the cheat sheets as expected.  

Package was freshly re-installed at v# ‘1.0.1.9000’.

image

### PR DESCRIPTION
**Pull request by kheal**

### CODE REVIEW

File: R/shortcuts.R [hunk 1]
```diff
@@ -30,6 +30,6 @@ cheat <- function(sheet) {
 
   sheet <- paste0(sheet, ".pdf")
 
-  fpath <- system.file("extdata/cheatsheets", sheet, package = "integral") %>% paste0("'", ., "'")
```
Comment (jzadra) [inline R/shortcuts.R:33]: This weird paste was something that was needed for some platforms that can't handle spaces in a path

Comment (jzadra) [reply R/shortcuts.R:33]: image

Comment (kheal) [reply R/shortcuts.R:33]: Oh funky - so I fixed it for windows but broke it for mac (and presumably linux). Whoops!
